version: '3.8'

services:
  basic-postgres:
    image: postgres:14.1-alpine
    container_name: basic-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4y7sV96vA9wv46VR
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4y7sV96vA9wv46VR
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - basic-postgres
volumes:
  postgres_data: